import { z } from 'zod'

// Define el esquema de un permiso
// Sirve para validar los datos de un permiso antes de enviarlos al servidor o de mostrarlos en la aplicación
// El esquema de un permiso es un objeto que tiene las siguientes propiedades:
export const permissionSchema = z.object({
    id: z.uuid(),
    name: z.string().max(100),
    description: z.string().max(255),
    module: z.string().max(50),
    action: z.string().max(50),
})

// Define el tipo Permission que es el tipo inferido del esquema permissionSchema
export type Permission = z.infer<typeof permissionSchema>
export type PermissionFormData = Pick<Permission, 'name' | 'description' | 'module' | 'action'>

// Define el esquema de un rol
// Sirve para validar los datos de un rol antes de enviarlos al servidor o de mostrarlos en la aplicación
// El esquema de un rol es un objeto que tiene las siguientes propiedades:
export const roleSchema = z.object({
    id: z.uuid(),
    name: z.string().max(100),
    description: z.string().optional(),
    permissions: z.array(permissionSchema).optional(),
})

// Define el tipo Role que es el tipo inferido del esquema roleSchema
export type Role = z.infer<typeof roleSchema>
export type RoleFormData = Pick<Role, 'name' | 'description'>

// Define el esquema de un token
// Sirve para validar los datos de un token antes de enviarlos al servidor o de mostrarlos en la aplicación
// El esquema de un token es un objeto que tiene las siguientes propiedades:
export const tokenSchema = z.object({
    id: z.uuid(),
    token: z.string().length(6),
    userId: z.uuid(),
    createdAt: z.date(),
    expiresAt: z.date(),
})

// Define el tipo Token que es el tipo inferido del esquema tokenSchema
export type Token = z.infer<typeof tokenSchema>
export type TokenFormData = Pick<Token, 'token' | 'userId'>

// Define el esquema de un usuario
// Sirve para validar los datos de un usuario antes de enviarlos al servidor o de mostrarlos en la aplicación
// El esquema de un usuario es un objeto que tiene las siguientes propiedades:

export const authSchema = z.object({
    name: z.string().max(100),
    rut: z.string().max(50),
    phone: z.string().max(15),
    age: z.number().int().positive(),
    email: z.email(),
    password: z.string().min(6).max(100),
    current_password: z.string().min(6).max(100),
    password_confirmation: z.string().min(6).max(100),
    token: z.string().length(6),
})
export type Auth = z.infer<typeof authSchema>
export type UserLoginForm = Pick<Auth   , 'email' | 'password'>
export type UserRegistrationForm = Pick<Auth, 'name' | 'email' | 'password' | 'password_confirmation' | 'age' | 'phone' | 'rut' >
export type RequestConfirmationCodeForm = Pick<Auth, 'email'>
export type ForgotPasswordForm = Pick<Auth, 'email'>
export type NewPasswordForm = Pick<Auth, 'password' | 'password_confirmation'>
export type UpdateCurrentUserPasswordForm = Pick<Auth, 'current_password' | 'password' | 'password_confirmation'>
export type ConfirmToken = Pick<Auth, 'token'>
export type CheckPasswordForm = Pick<Auth, 'password'>

export const userSchema = z.object({
    id: z.uuid(),
    rut: z.string().max(50),
    name: z.string().max(100),
    email: z.email(),
    phone: z.string().max(15),
    password: z.string().optional(), // Opcional porque no siempre se incluye en las respuestas
    age: z.number().int().positive().optional(),
    confirmed: z.boolean().default(false),
    createdAt: z.string().transform((date) => new Date(date)),
    updatedAt: z.string().transform((date) => new Date(date)),
    deletedAt: z.string().transform((date) => new Date(date)).nullable(),
    roles: z.array(roleSchema).optional(),
    tokens: z.array(tokenSchema).optional(),
})

// Define el tipo User que es el tipo inferido del esquema userSchema
export type User = z.infer<typeof userSchema>
export type UserFormData = Pick<User, 'name' | 'email' | 'password'  | 'age' | 'phone' | 'rut'>
export type UserUpdateData = Pick<User, 'name' | 'email' | 'age' | 'phone' | 'rut'>
export type UserLoginData = Pick<User, 'email' | 'password'>
export type UserAuthResponse = Omit<User, 'password' | 'tokens'> & {
    token?: string
}

// Camera schemas and types

// Camera schema based on backend entity (backend/src/cameras/entities/camera.entity.ts)
export const cameraSchema = z.object({
    id: z.string().uuid(),
    name: z.string().max(150),
    location: z.string().max(200).optional(),
    // mountPath is optional and generated by backend
    mountPath: z.string().max(150).optional(),
    registeredInMediamtx: z.boolean().optional(),
    active: z.boolean().optional(),
    // roles may be present in populated responses
    roles: z.array(roleSchema).optional(),
})

export type Camera = z.infer<typeof cameraSchema>

// CreateCameraDto (backend/src/cameras/dto/create-camera.dto.ts)
export const createCameraSchema = z.object({
    name: z.string().min(1).max(150),
    location: z.string().max(200).optional(),
    // Plain source URL provided by client; backend will encrypt it
    sourceUrl: z.string().min(1).max(500),
    // optional: whether the camera is active
    active: z.boolean().optional(),
    // role IDs that will be associated to the camera
    roleIds: z.array(z.string().uuid()).optional(),
})

export type CreateCameraFormData = z.infer<typeof createCameraSchema>

export type UpdateCameraFormData = Partial<CreateCameraFormData> & {
    // mountPath cannot be updated via API
    mountPath?: never
}
